(define (Driver::loop)
  (let ((ε (Structures::Environment::extend
               (Structures::Frame::make '() '())
               Structures::Environment::builtins)))
    (define (loop)
      (Driver:::prompt)
      (let* ((𝘌 (read))
             (a (Eval::eval 𝘌 ε)))
        (Driver:::print a))
      (loop))
    (loop)))

(define (Driver:::prompt) (newline) (newline) (display ">> "))
(define (Driver:::print obj)
  (newline) (display "# ") (newline)
  (if (Structures::Closure::p obj)
      (display (list 'compound (procedure-parameters obj) (procedure-body obj) '<procedure-env>))
      (display obj)))
